# Generated by Django 2.1.5 on 2019-02-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchenge_date', models.DateTimeField(verbose_name='日付')),
                ('detail', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
