# Generated by Django 2.1.5 on 2019-02-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='exchenge_date',
            field=models.DateTimeField(),
        ),
    ]
