# Generated by Django 2.1.5 on 2019-05-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20190223_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='category',
            field=models.CharField(default='食費', max_length=10),
            preserve_default=False,
        ),
    ]
