# Generated by Django 2.1.5 on 2019-05-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_money_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='money',
            name='category',
            field=models.CharField(choices=[('家賃', '家賃'), ('通信費', '通信費'), ('保険費', '保険費'), ('クレカ', 'クレカ'), ('ガソリン代', 'ガソリン代'), ('雑費', '雑費'), ('光熱費', '光熱費'), ('車代', '車代'), ('奨学金', '奨学金'), ('ローン', 'ローン'), ('食費', '食費'), ('交遊費', '交遊費'), ('NHK受信料', 'NHK受信料'), ('その他', 'その他')], max_length=10, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='money',
            name='detail',
            field=models.CharField(max_length=200, verbose_name='用途'),
        ),
    ]
