# Generated by Django 2.1.5 on 2019-06-02 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auto_20190522_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000000)], verbose_name='金額'),
        ),
    ]
