# Generated by Django 2.1.5 on 2019-06-02 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_auto_20190602_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Money')),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
    ]
